const villageSurveyData = [
    // Sukinda Block Villages
    {
      Block: "Sukinda",
      VillageName: "Sukinda Central",
      TotalHouseHoldsSurveyed: 750,
      TotalPopulationSurveyed: 3200,
      villageAgeDemographic: { "0-18": 35, "19-45": 40, "46-60": 15, "60+": 10 },
      PopulationGenderDemographic: { Male: 52, Female: 48 },
      PopulationCategoryDemographic: { SC: 25, ST: 30, OBC: 35, General: 10 },
      Skilling: { Skilled: 60, Unskilled: 40 },
      SkilledGenderDemographic: { Male: 65, Female: 35 },
      Literacy: { Literate: 70, Illiterate: 20, Semiliterate: 10 },
      AWCNutritionReceived: 85,
      HouseHoldsRegisteredWithAwc: 90,
      HouseHoldsWithHealthInsurance: 45,
      HouseHoldsWithMCPCard: 60,
      ChronicDiseasesData: { Diabetes: 8, HyperTension: 12, Asthma: 5, Arthritis: 7, Cancer: 1, HeartDisease: 4 },
      HouseHoldsOwnership: { OwnHouse: 80, Others: 20 },
      TypeofHouse: { Pucca: 50, Kaccha: 30, SemiPucca: 20 },
      HouseUnderSchemes: 40,
      TotalVillageAnnualIncome: 12000000,
      AvgAnnualIncome: 16000,
      IncomeBreakDown: { "Agriculture(crop)": 45, "Agriculture(non-crop)": 15, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 9500000,
      AvgAnnualVillageExpenditure: 12667,
      ExpenditureBreakdown: { Food: 40, Housing: 20, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 60, TubeWell: 25, Well: 10, Others: 5 },
      ToiletsAtHome: 550,
      PublicToiletAccess: 200,
      DrainageConnectivity: 400,
      OpenDefacation: 150,
      BathroomAtHome: 450,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda East",
      TotalHouseHoldsSurveyed: 600,
      TotalPopulationSurveyed: 2600,
      villageAgeDemographic: { "0-18": 40, "19-45": 35, "46-60": 15, "60+": 10 },
      PopulationGenderDemographic: { Male: 51, Female: 49 },
      PopulationCategoryDemographic: { SC: 20, ST: 35, OBC: 30, General: 15 },
      Skilling: { Skilled: 55, Unskilled: 45 },
      SkilledGenderDemographic: { Male: 70, Female: 30 },
      Literacy: { Literate: 65, Illiterate: 25, Semiliterate: 10 },
      AWCNutritionReceived: 80,
      HouseHoldsRegisteredWithAwc: 85,
      HouseHoldsWithHealthInsurance: 40,
      HouseHoldsWithMCPCard: 55,
      ChronicDiseasesData: { Diabetes: 7, HyperTension: 10, Asthma: 6, Arthritis: 5, Cancer: 1, HeartDisease: 3 },
      HouseHoldsOwnership: { OwnHouse: 75, Others: 25 },
      TypeofHouse: { Pucca: 45, Kaccha: 35, SemiPucca: 20 },
      HouseUnderSchemes: 35,
      TotalVillageAnnualIncome: 9000000,
      AvgAnnualIncome: 15000,
      IncomeBreakDown: { "Agriculture(crop)": 50, "Agriculture(non-crop)": 10, Service: 15, NonAgriculture: 15, Others: 10 },
      TotalAnnualVillageExpenditure: 7200000,
      AvgAnnualVillageExpenditure: 12000,
      ExpenditureBreakdown: { Food: 45, Housing: 20, Education: 15, HealthCare: 10, Others: 10 },
      ReliableWaterAvailability: 30,
      SourceofWater: { PipedWater: 50, TubeWell: 30, Well: 15, Others: 5 },
      ToiletsAtHome: 400,
      PublicToiletAccess: 150,
      DrainageConnectivity: 300,
      OpenDefacation: 200,
      BathroomAtHome: 350,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda West",
      TotalHouseHoldsSurveyed: 700,
      TotalPopulationSurveyed: 3000,
      villageAgeDemographic: { "0-18": 30, "19-45": 45, "46-60": 15, "60+": 10 },
      PopulationGenderDemographic: { Male: 53, Female: 47 },
      PopulationCategoryDemographic: { SC: 15, ST: 40, OBC: 30, General: 15 },
      Skilling: { Skilled: 65, Unskilled: 35 },
      SkilledGenderDemographic: { Male: 60, Female: 40 },
      Literacy: { Literate: 75, Illiterate: 15, Semiliterate: 10 },
      AWCNutritionReceived: 90,
      HouseHoldsRegisteredWithAwc: 95,
      HouseHoldsWithHealthInsurance: 50,
      HouseHoldsWithMCPCard: 65,
      ChronicDiseasesData: { Diabetes: 6, HyperTension: 11, Asthma: 4, Arthritis: 6, Cancer: 1, HeartDisease: 3 },
      HouseHoldsOwnership: { OwnHouse: 85, Others: 15 },
      TypeofHouse: { Pucca: 55, Kaccha: 25, SemiPucca: 20 },
      HouseUnderSchemes: 45,
      TotalVillageAnnualIncome: 11000000,
      AvgAnnualIncome: 15714,
      IncomeBreakDown: { "Agriculture(crop)": 40, "Agriculture(non-crop)": 20, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 8800000,
      AvgAnnualVillageExpenditure: 12571,
      ExpenditureBreakdown: { Food: 35, Housing: 25, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 65, TubeWell: 20, Well: 10, Others: 5 },
      ToiletsAtHome: 500,
      PublicToiletAccess: 180,
      DrainageConnectivity: 350,
      OpenDefacation: 120,
      BathroomAtHome: 400,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda North",
      TotalHouseHoldsSurveyed: 650,
      TotalPopulationSurveyed: 2800,
      villageAgeDemographic: { "0-18": 38, "19-45": 38, "46-60": 14, "60+": 10 },
      PopulationGenderDemographic: { Male: 50, Female: 50 },
      PopulationCategoryDemographic: { SC: 30, ST: 25, OBC: 35, General: 10 },
      Skilling: { Skilled: 58, Unskilled: 42 },
      SkilledGenderDemographic: { Male: 68, Female: 32 },
      Literacy: { Literate: 68, Illiterate: 22, Semiliterate: 10 },
      AWCNutritionReceived: 82,
      HouseHoldsRegisteredWithAwc: 88,
      HouseHoldsWithHealthInsurance: 42,
      HouseHoldsWithMCPCard: 58,
      ChronicDiseasesData: { Diabetes: 9, HyperTension: 13, Asthma: 5, Arthritis: 6, Cancer: 1, HeartDisease: 4 },
      HouseHoldsOwnership: { OwnHouse: 78, Others: 22 },
      TypeofHouse: { Pucca: 48, Kaccha: 32, SemiPucca: 20 },
      HouseUnderSchemes: 38,
      TotalVillageAnnualIncome: 10000000,
      AvgAnnualIncome: 15385,
      IncomeBreakDown: { "Agriculture(crop)": 45, "Agriculture(non-crop)": 15, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 8000000,
      AvgAnnualVillageExpenditure: 12308,
      ExpenditureBreakdown: { Food: 40, Housing: 20, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 60, TubeWell: 25, Well: 10, Others: 5 },
      ToiletsAtHome: 450,
      PublicToiletAccess: 170,
      DrainageConnectivity: 320,
      OpenDefacation: 180,
      BathroomAtHome: 380,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda South",
      TotalHouseHoldsSurveyed: 550,
      TotalPopulationSurveyed: 2400,
      villageAgeDemographic: { "0-18": 36, "19-45": 42, "46-60": 12, "60+": 10 },
      PopulationGenderDemographic: { Male: 52, Female: 48 },
      PopulationCategoryDemographic: { SC: 20, ST: 35, OBC: 30, General: 15 },
      Skilling: { Skilled: 62, Unskilled: 38 },
      SkilledGenderDemographic: { Male: 63, Female: 37 },
      Literacy: { Literate: 72, Illiterate: 18, Semiliterate: 10 },
      AWCNutritionReceived: 87,
      HouseHoldsRegisteredWithAwc: 92,
      HouseHoldsWithHealthInsurance: 48,
      HouseHoldsWithMCPCard: 62,
      ChronicDiseasesData: { Diabetes: 7, HyperTension: 11, Asthma: 4, Arthritis: 5, Cancer: 1, HeartDisease: 3 },
      HouseHoldsOwnership: { OwnHouse: 82, Others: 18 },
      TypeofHouse: { Pucca: 52, Kaccha: 28, SemiPucca: 20 },
      HouseUnderSchemes: 42,
      TotalVillageAnnualIncome: 8500000,
      AvgAnnualIncome: 15455,
      IncomeBreakDown: { "Agriculture(crop)": 50, "Agriculture(non-crop)": 10, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 6800000,
      AvgAnnualVillageExpenditure: 12364,
      ExpenditureBreakdown: { Food: 45, Housing: 20, Education: 15, HealthCare: 10, Others: 10 },
      ReliableWaterAvailability: 30,
      SourceofWater: { PipedWater: 55, TubeWell: 30, Well: 10, Others: 5 },
      ToiletsAtHome: 350,
      PublicToiletAccess: 140,
      DrainageConnectivity: 280,
      OpenDefacation: 170,
      BathroomAtHome: 300,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda Hills",
      TotalHouseHoldsSurveyed: 800,
      TotalPopulationSurveyed: 3400,
      villageAgeDemographic: { "0-18": 32, "19-45": 44, "46-60": 14, "60+": 10 },
      PopulationGenderDemographic: { Male: 51, Female: 49 },
      PopulationCategoryDemographic: { SC: 15, ST: 45, OBC: 25, General: 15 },
      Skilling: { Skilled: 60, Unskilled: 40 },
      SkilledGenderDemographic: { Male: 67, Female: 33 },
      Literacy: { Literate: 70, Illiterate: 20, Semiliterate: 10 },
      AWCNutritionReceived: 85,
      HouseHoldsRegisteredWithAwc: 90,
      HouseHoldsWithHealthInsurance: 45,
      HouseHoldsWithMCPCard: 60,
      ChronicDiseasesData: { Diabetes: 8, HyperTension: 12, Asthma: 5, Arthritis: 7, Cancer: 1, HeartDisease: 4 },
      HouseHoldsOwnership: { OwnHouse: 80, Others: 20 },
      TypeofHouse: { Pucca: 50, Kaccha: 30, SemiPucca: 20 },
      HouseUnderSchemes: 40,
      TotalVillageAnnualIncome: 13000000,
      AvgAnnualIncome: 16250,
      IncomeBreakDown: { "Agriculture(crop)": 45, "Agriculture(non-crop)": 15, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 10400000,
      AvgAnnualVillageExpenditure: 13000,
      ExpenditureBreakdown: { Food: 40, Housing: 20, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 60, TubeWell: 25, Well: 10, Others: 5 },
      ToiletsAtHome: 600,
      PublicToiletAccess: 200,
      DrainageConnectivity: 400,
      OpenDefacation: 150,
      BathroomAtHome: 500,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda Valley",
      TotalHouseHoldsSurveyed: 720,
      TotalPopulationSurveyed: 3100,
      villageAgeDemographic: { "0-18": 34, "19-45": 41, "46-60": 15, "60+": 10 },
      PopulationGenderDemographic: { Male: 52, Female: 48 },
      PopulationCategoryDemographic: { SC: 25, ST: 30, OBC: 35, General: 10 },
      Skilling: { Skilled: 61, Unskilled: 39 },
      SkilledGenderDemographic: { Male: 64, Female: 36 },
      Literacy: { Literate: 71, Illiterate: 19, Semiliterate: 10 },
      AWCNutritionReceived: 86,
      HouseHoldsRegisteredWithAwc: 91,
      HouseHoldsWithHealthInsurance: 46,
      HouseHoldsWithMCPCard: 61,
      ChronicDiseasesData: { Diabetes: 7, HyperTension: 11, Asthma: 5, Arthritis: 6, Cancer: 1, HeartDisease: 3 },
      HouseHoldsOwnership: { OwnHouse: 81, Others: 19 },
      TypeofHouse: { Pucca: 51, Kaccha: 29, SemiPucca: 20 },
      HouseUnderSchemes: 41,
      TotalVillageAnnualIncome: 11500000,
      AvgAnnualIncome: 15972,
      IncomeBreakDown: { "Agriculture(crop)": 40, "Agriculture(non-crop)": 20, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 9200000,
      AvgAnnualVillageExpenditure: 12778,
      ExpenditureBreakdown: { Food: 35, Housing: 25, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 65, TubeWell: 20, Well: 10, Others: 5 },
      ToiletsAtHome: 520,
      PublicToiletAccess: 190,
      DrainageConnectivity: 360,
      OpenDefacation: 140,
      BathroomAtHome: 420,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda Plains",
      TotalHouseHoldsSurveyed: 680,
      TotalPopulationSurveyed: 2900,
      villageAgeDemographic: { "0-18": 37, "19-45": 39, "46-60": 14, "60+": 10 },
      PopulationGenderDemographic: { Male: 51, Female: 49 },
      PopulationCategoryDemographic: { SC: 20, ST: 35, OBC: 30, General: 15 },
      Skilling: { Skilled: 59, Unskilled: 41 },
      SkilledGenderDemographic: { Male: 66, Female: 34 },
      Literacy: { Literate: 69, Illiterate: 21, Semiliterate: 10 },
      AWCNutritionReceived: 83,
      HouseHoldsRegisteredWithAwc: 89,
      HouseHoldsWithHealthInsurance: 43,
      HouseHoldsWithMCPCard: 57,
      ChronicDiseasesData: { Diabetes: 8, HyperTension: 12, Asthma: 6, Arthritis: 5, Cancer: 1, HeartDisease: 4 },
      HouseHoldsOwnership: { OwnHouse: 79, Others: 21 },
      TypeofHouse: { Pucca: 49, Kaccha: 31, SemiPucca: 20 },
      HouseUnderSchemes: 39,
      TotalVillageAnnualIncome: 10500000,
      AvgAnnualIncome: 15441,
      IncomeBreakDown: { "Agriculture(crop)": 45, "Agriculture(non-crop)": 15, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 8400000,
      AvgAnnualVillageExpenditure: 12353,
      ExpenditureBreakdown: { Food: 40, Housing: 20, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 30,
      SourceofWater: { PipedWater: 55, TubeWell: 30, Well: 10, Others: 5 },
      ToiletsAtHome: 480,
      PublicToiletAccess: 160,
      DrainageConnectivity: 340,
      OpenDefacation: 160,
      BathroomAtHome: 390,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda Ridge",
      TotalHouseHoldsSurveyed: 730,
      TotalPopulationSurveyed: 3100,
      villageAgeDemographic: { "0-18": 33, "19-45": 43, "46-60": 14, "60+": 10 },
      PopulationGenderDemographic: { Male: 53, Female: 47 },
      PopulationCategoryDemographic: { SC: 15, ST: 40, OBC: 30, General: 15 },
      Skilling: { Skilled: 63, Unskilled: 37 },
      SkilledGenderDemographic: { Male: 62, Female: 38 },
      Literacy: { Literate: 73, Illiterate: 17, Semiliterate: 10 },
      AWCNutritionReceived: 88,
      HouseHoldsRegisteredWithAwc: 93,
      HouseHoldsWithHealthInsurance: 49,
      HouseHoldsWithMCPCard: 63,
      ChronicDiseasesData: { Diabetes: 6, HyperTension: 10, Asthma: 4, Arthritis: 6, Cancer: 1, HeartDisease: 3 },
      HouseHoldsOwnership: { OwnHouse: 83, Others: 17 },
      TypeofHouse: { Pucca: 53, Kaccha: 27, SemiPucca: 20 },
      HouseUnderSchemes: 43,
      TotalVillageAnnualIncome: 11800000,
      AvgAnnualIncome: 16164,
      IncomeBreakDown: { "Agriculture(crop)": 40, "Agriculture(non-crop)": 20, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 9440000,
      AvgAnnualVillageExpenditure: 12931,
      ExpenditureBreakdown: { Food: 35, Housing: 25, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 60, TubeWell: 25, Well: 10, Others: 5 },
      ToiletsAtHome: 530,
      PublicToiletAccess: 185,
      DrainageConnectivity: 370,
      OpenDefacation: 130,
      BathroomAtHome: 430,
    },
    {
      Block: "Sukinda",
      VillageName: "Sukinda Lowlands",
      TotalHouseHoldsSurveyed: 670,
      TotalPopulationSurveyed: 2900,
      villageAgeDemographic: { "0-18": 35, "19-45": 40, "46-60": 15, "60+": 10 },
      PopulationGenderDemographic: { Male: 52, Female: 48 },
      PopulationCategoryDemographic: { SC: 25, ST: 30, OBC: 35, General: 10 },
      Skilling: { Skilled: 57, Unskilled: 43 },
      SkilledGenderDemographic: { Male: 69, Female: 31 },
      Literacy: { Literate: 67, Illiterate: 23, Semiliterate: 10 },
      AWCNutritionReceived: 84,
      HouseHoldsRegisteredWithAwc: 87,
      HouseHoldsWithHealthInsurance: 41,
      HouseHoldsWithMCPCard: 56,
      ChronicDiseasesData: { Diabetes: 9, HyperTension: 13, Asthma: 5, Arthritis: 6, Cancer: 1, HeartDisease: 4 },
      HouseHoldsOwnership: { OwnHouse: 77, Others: 23 },
      TypeofHouse: { Pucca: 47, Kaccha: 33, SemiPucca: 20 },
      HouseUnderSchemes: 37,
      TotalVillageAnnualIncome: 10200000,
      AvgAnnualIncome: 15224,
      IncomeBreakDown: { "Agriculture(crop)": 45, "Agriculture(non-crop)": 15, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 8160000,
      AvgAnnualVillageExpenditure: 12179,
      ExpenditureBreakdown: { Food: 40, Housing: 20, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 30,
      SourceofWater: { PipedWater: 50, TubeWell: 30, Well: 15, Others: 5 },
      ToiletsAtHome: 470,
      PublicToiletAccess: 150,
      DrainageConnectivity: 330,
      OpenDefacation: 170,
      BathroomAtHome: 380,
    },
  
    // Danagadi Block Villages
    {
      Block: "Danagadi",
      VillageName: "Danagadi Central",
      TotalHouseHoldsSurveyed: 700,
      TotalPopulationSurveyed: 3000,
      villageAgeDemographic: { "0-18": 36, "19-45": 41, "46-60": 13, "60+": 10 },
      PopulationGenderDemographic: { Male: 51, Female: 49 },
      PopulationCategoryDemographic: { SC: 20, ST: 25, OBC: 40, General: 15 },
      Skilling: { Skilled: 64, Unskilled: 36 },
      SkilledGenderDemographic: { Male: 61, Female: 39 },
      Literacy: { Literate: 74, Illiterate: 16, Semiliterate: 10 },
      AWCNutritionReceived: 89,
      HouseHoldsRegisteredWithAwc: 94,
      HouseHoldsWithHealthInsurance: 47,
      HouseHoldsWithMCPCard: 64,
      ChronicDiseasesData: { Diabetes: 6, HyperTension: 10, Asthma: 4, Arthritis: 5, Cancer: 1, HeartDisease: 3 },
      HouseHoldsOwnership: { OwnHouse: 84, Others: 16 },
      TypeofHouse: { Pucca: 54, Kaccha: 26, SemiPucca: 20 },
      HouseUnderSchemes: 44,
      TotalVillageAnnualIncome: 11200000,
      AvgAnnualIncome: 16000,
      IncomeBreakDown: { "Agriculture(crop)": 40, "Agriculture(non-crop)": 20, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 8960000,
      AvgAnnualVillageExpenditure: 12800,
      ExpenditureBreakdown: { Food: 35, Housing: 25, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 60, TubeWell: 25, Well: 10, Others: 5 },
      ToiletsAtHome: 500,
      PublicToiletAccess: 180,
      DrainageConnectivity: 350,
      OpenDefacation: 130,
      BathroomAtHome: 400,
    },
    {
      Block: "Danagadi",
      VillageName: "Danagadi East",
      TotalHouseHoldsSurveyed: 650,
      TotalPopulationSurveyed: 2800,
      villageAgeDemographic: { "0-18": 38, "19-45": 39, "46-60": 13, "60+": 10 },
      PopulationGenderDemographic: { Male: 52, Female: 48 },
      PopulationCategoryDemographic: { SC: 25, ST: 20, OBC: 40, General: 15 },
      Skilling: { Skilled: 62, Unskilled: 38 },
      SkilledGenderDemographic: { Male: 63, Female: 37 },
      Literacy: { Literate: 72, Illiterate: 18, Semiliterate: 10 },
      AWCNutritionReceived: 87,
      HouseHoldsRegisteredWithAwc: 92,
      HouseHoldsWithHealthInsurance: 44,
      HouseHoldsWithMCPCard: 59,
      ChronicDiseasesData: { Diabetes: 7, HyperTension: 11, Asthma: 5, Arthritis: 6, Cancer: 1, HeartDisease: 3 },
      HouseHoldsOwnership: { OwnHouse: 82, Others: 18 },
      TypeofHouse: { Pucca: 52, Kaccha: 28, SemiPucca: 20 },
      HouseUnderSchemes: 42,
      TotalVillageAnnualIncome: 10400000,
      AvgAnnualIncome: 16000,
      IncomeBreakDown: { "Agriculture(crop)": 45, "Agriculture(non-crop)": 15, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 8320000,
      AvgAnnualVillageExpenditure: 12800,
      ExpenditureBreakdown: { Food: 40, Housing: 20, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 30,
      SourceofWater: { PipedWater: 55, TubeWell: 30, Well: 10, Others: 5 },
      ToiletsAtHome: 450,
      PublicToiletAccess: 160,
      DrainageConnectivity: 320,
      OpenDefacation: 150,
      BathroomAtHome: 370,
    },
    {
      Block: "Danagadi",
      VillageName: "Danagadi West",
      TotalHouseHoldsSurveyed: 600,
      TotalPopulationSurveyed: 2600,
      villageAgeDemographic: { "0-18": 37, "19-45": 40, "46-60": 13, "60+": 10 },
      PopulationGenderDemographic: { Male: 51, Female: 49 },
      PopulationCategoryDemographic: { SC: 20, ST: 25, OBC: 35, General: 20 },
      Skilling: { Skilled: 60, Unskilled: 40 },
      SkilledGenderDemographic: { Male: 65, Female: 35 },
      Literacy: { Literate: 70, Illiterate: 20, Semiliterate: 10 },
      AWCNutritionReceived: 85,
      HouseHoldsRegisteredWithAwc: 90,
      HouseHoldsWithHealthInsurance: 43,
      HouseHoldsWithMCPCard: 58,
      ChronicDiseasesData: { Diabetes: 8, HyperTension: 12, Asthma: 5, Arthritis: 6, Cancer: 1, HeartDisease: 4 },
      HouseHoldsOwnership: { OwnHouse: 80, Others: 20 },
      TypeofHouse: { Pucca: 50, Kaccha: 30, SemiPucca: 20 },
      HouseUnderSchemes: 40,
      TotalVillageAnnualIncome: 9600000,
      AvgAnnualIncome: 16000,
      IncomeBreakDown: { "Agriculture(crop)": 40, "Agriculture(non-crop)": 20, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 7680000,
      AvgAnnualVillageExpenditure: 12800,
      ExpenditureBreakdown: { Food: 35, Housing: 25, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 60, TubeWell: 25, Well: 10, Others: 5 },
      ToiletsAtHome: 400,
      PublicToiletAccess: 150,
      DrainageConnectivity: 300,
      OpenDefacation: 160,
      BathroomAtHome: 350,
    },
    {
      Block: "Danagadi",
      VillageName: "Danagadi South",
      TotalHouseHoldsSurveyed: 550,
      TotalPopulationSurveyed: 2400,
      villageAgeDemographic: { "0-18": 35, "19-45": 42, "46-60": 13, "60+": 10 },
      PopulationGenderDemographic: { Male: 52, Female: 48 },
      PopulationCategoryDemographic: { SC: 25, ST: 20, OBC: 40, General: 15 },
      Skilling: { Skilled: 58, Unskilled: 42 },
      SkilledGenderDemographic: { Male: 67, Female: 33 },
      Literacy: { Literate: 68, Illiterate: 22, Semiliterate: 10 },
      AWCNutritionReceived: 83,
      HouseHoldsRegisteredWithAwc: 88,
      HouseHoldsWithHealthInsurance: 41,
      HouseHoldsWithMCPCard: 56,
      ChronicDiseasesData: { Diabetes: 9, HyperTension: 13, Asthma: 6, Arthritis: 5, Cancer: 1, HeartDisease: 4 },
      HouseHoldsOwnership: { OwnHouse: 78, Others: 22 },
      TypeofHouse: { Pucca: 48, Kaccha: 32, SemiPucca: 20 },
      HouseUnderSchemes: 38,
      TotalVillageAnnualIncome: 8800000,
      AvgAnnualIncome: 16000,
      IncomeBreakDown: { "Agriculture(crop)": 45, "Agriculture(non-crop)": 15, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 7040000,
      AvgAnnualVillageExpenditure: 12800,
      ExpenditureBreakdown: { Food: 40, Housing: 20, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 30,
      SourceofWater: { PipedWater: 50, TubeWell: 30, Well: 15, Others: 5 },
      ToiletsAtHome: 350,
      PublicToiletAccess: 140,
      DrainageConnectivity: 280,
      OpenDefacation: 170,
      BathroomAtHome: 300,
    },
    {
      Block: "Danagadi",
      VillageName: "Danagadi North",
      TotalHouseHoldsSurveyed: 720,
      TotalPopulationSurveyed: 3100,
      villageAgeDemographic: { "0-18": 34, "19-45": 43, "46-60": 13, "60+": 10 },
      PopulationGenderDemographic: { Male: 51, Female: 49 },
      PopulationCategoryDemographic: { SC: 20, ST: 25, OBC: 35, General: 20 },
      Skilling: { Skilled: 63, Unskilled: 37 },
      SkilledGenderDemographic: { Male: 62, Female: 38 },
      Literacy: { Literate: 73, Illiterate: 17, Semiliterate: 10 },
      AWCNutritionReceived: 88,
      HouseHoldsRegisteredWithAwc: 93,
      HouseHoldsWithHealthInsurance: 46,
      HouseHoldsWithMCPCard: 61,
      ChronicDiseasesData: { Diabetes: 7, HyperTension: 11, Asthma: 5, Arthritis: 6, Cancer: 1, HeartDisease: 3 },
      HouseHoldsOwnership: { OwnHouse: 83, Others: 17 },
      TypeofHouse: { Pucca: 53, Kaccha: 27, SemiPucca: 20 },
      HouseUnderSchemes: 43,
      TotalVillageAnnualIncome: 10800000,
      AvgAnnualIncome: 15000,
      IncomeBreakDown: { "Agriculture(crop)": 40, "Agriculture(non-crop)": 20, Service: 20, NonAgriculture: 10, Others: 10 },
      TotalAnnualVillageExpenditure: 8640000,
      AvgAnnualVillageExpenditure: 12000,
      ExpenditureBreakdown: { Food: 35, Housing: 25, Education: 15, HealthCare: 15, Others: 10 },
      ReliableWaterAvailability: 40,
      SourceofWater: { PipedWater: 60, TubeWell: 25, Well: 10, Others: 5 },
      ToiletsAtHome: 520,
      PublicToiletAccess: 190,
      DrainageConnectivity: 360,
      OpenDefacation: 140,
      BathroomAtHome: 420,
    },
  ];
  
  export default villageSurveyData;